-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TableProgressTracking/schema/tables-generated.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/table_progress_tracking (
  tpt_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  page_id INTEGER UNSIGNED NOT NULL,
  table_id INTEGER NOT NULL,
  user_id INTEGER UNSIGNED NOT NULL,
  entity_id VARCHAR(255) NOT NULL,
  tpt_timestamp BLOB NOT NULL
);

CREATE INDEX tpt_user_page_table ON /*_*/table_progress_tracking (user_id, page_id, table_id);

CREATE INDEX tpt_page_table ON /*_*/table_progress_tracking (page_id, table_id);

CREATE UNIQUE INDEX tpt_unique_progress ON /*_*/table_progress_tracking (
  user_id, page_id, table_id, entity_id
);
