-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TableProgressTracking/schema/tables-generated.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/table_progress_tracking (
  tpt_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  page_id INT UNSIGNED NOT NULL,
  table_id INT NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  entity_id VARCHAR(255) NOT NULL,
  tpt_timestamp BINARY(14) NOT NULL,
  INDEX tpt_user_page_table (user_id, page_id, table_id),
  INDEX tpt_page_table (page_id, table_id),
  UNIQUE INDEX tpt_unique_progress (
    user_id, page_id, table_id, entity_id
  ),
  PRIMARY KEY(tpt_id)
) /*$wgDBTableOptions*/;
