-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/TableProgressTracking/schema/tables-generated.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE table_progress_tracking (
  tpt_id BIGSERIAL NOT NULL,
  page_id INT NOT NULL,
  table_id INT NOT NULL,
  user_id INT NOT NULL,
  entity_id VARCHAR(255) NOT NULL,
  tpt_timestamp TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(tpt_id)
);

CREATE INDEX tpt_user_page_table ON table_progress_tracking (user_id, page_id, table_id);

CREATE INDEX tpt_page_table ON table_progress_tracking (page_id, table_id);

CREATE UNIQUE INDEX tpt_unique_progress ON table_progress_tracking (
  user_id, page_id, table_id, entity_id
);
